/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ComparadorDeImagens.Program;

import ComparadorDeImagens.dao.ImagesDAO;
import ComparadorDeImagens.dao.ImagesDAO.ImageData;
import javax.swing.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.imageio.ImageIO;

public class GetImages extends javax.swing.JFrame {

    private List<ImageData> dateTimeImage;
    private DefaultListModel<String> listModel;
    private int currentIndex = -1;

    public GetImages() {
        initComponents();
        loadImagesFromDB();
        setupListListener();
        setLocationRelativeTo(null);
    }

    private void loadImagesFromDB() {
        ImagesDAO dao = new ImagesDAO();
        dateTimeImage = dao.getAllImagesDateTimes();

        listModel = new DefaultListModel<>();
        jList1.setModel(listModel);
        listModel.clear();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        for (ImageData item : dateTimeImage) {
            listModel.addElement(sdf.format(item.getDateTime()));
        }

        if (!dateTimeImage.isEmpty()) {
            currentIndex = 0;
            jList1.setSelectedIndex(0);
            showImageAtIndex(0);
        }
    }

    private void setupListListener() {
        jList1.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int index = jList1.getSelectedIndex();
                if (index >= 0 && index < dateTimeImage.size()) {
                    currentIndex = index;
                    showImageAtIndex(index);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        Proximo = new javax.swing.JButton();
        Anterior = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Inserction = new javax.swing.JButton();
        Bubble = new javax.swing.JButton();
        Quick = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(187, 248, 243));
        jPanel2.setForeground(new java.awt.Color(187, 248, 243));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jList1);

        jPanel1.setBackground(new java.awt.Color(187, 248, 243));
        jPanel1.setForeground(new java.awt.Color(187, 248, 243));

        Proximo.setText("Proximo");
        Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximoActionPerformed(evt);
            }
        });

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Inserction.setText("Inserction");
        Inserction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InserctionActionPerformed(evt);
            }
        });

        Bubble.setText("Bubble");
        Bubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BubbleActionPerformed(evt);
            }
        });

        Quick.setText("Quick");
        Quick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Inserction, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bubble, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Quick, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Quick, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bubble, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Inserction, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximoActionPerformed
        // TODO add your handling code here:
        if (dateTimeImage == null || dateTimeImage.isEmpty()) {
            return;
        }

        if (currentIndex < dateTimeImage.size() - 1) {
            currentIndex++;
        } else {
            currentIndex = 0; // volta ao início
        }

        jList1.setSelectedIndex(currentIndex);
        showImageAtIndex(currentIndex);
    }//GEN-LAST:event_ProximoActionPerformed

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed
        // TODO add your handling code here:
        if (dateTimeImage == null || dateTimeImage.isEmpty()) {
            return;
        }

        if (currentIndex > 0) {
            currentIndex--;
        } else {
            currentIndex = dateTimeImage.size() - 1; // vai pro final
        }

        jList1.setSelectedIndex(currentIndex);
        showImageAtIndex(currentIndex);
    }//GEN-LAST:event_AnteriorActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        if (dateTimeImage == null || dateTimeImage.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Não há imagens para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idx = jList1.getSelectedIndex();
        if (idx < 0 || idx >= dateTimeImage.size()) {
            JOptionPane.showMessageDialog(this, "Nenhuma imagem selecionada.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        ImageData item = dateTimeImage.get(idx);
        Timestamp dateTime = item.getDateTime();
        int id = item.getId();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String formatted = (dateTime != null) ? sdf.format(dateTime) : "desconhecido";

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir a imagem de " + formatted + "?",
                "Confirmar exclusão",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return; // usuário cancelou
        }

        ImagesDAO dao = new ImagesDAO();
        try {
            // Chama o método deleta do DAO passando o datetime da imagem selecionada.
            // Observação: o método DeletImage pode retornar void ou boolean. Aqui assumimos que
            // ele lança exceção em caso de erro. Se o seu DAO retornar boolean, ajuste conforme necessário.
            //dao.DeletImage(dateTime);
            dao.DeletImage(id); 
            
            // Atualiza a lista em memória e o JList
            dateTimeImage.remove(idx);
            listModel.remove(idx);

            if (!dateTimeImage.isEmpty()) {
                currentIndex = Math.min(idx, dateTimeImage.size() - 1);
                jList1.setSelectedIndex(currentIndex);
                showImageAtIndex(currentIndex);
            } else {
                currentIndex = -1;
                jLabel1.setIcon(null);
            }

            JOptionPane.showMessageDialog(this, "Imagem excluída com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erro ao excluir a imagem: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ExcluirActionPerformed

    private void InserctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserctionActionPerformed
        if (dateTimeImage == null || dateTimeImage.isEmpty()) return;
        ordenarComContagem("insertion");
    }//GEN-LAST:event_InserctionActionPerformed

    private void BubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BubbleActionPerformed
        if (dateTimeImage == null || dateTimeImage.isEmpty()) return;
        ordenarComContagem("bubble");
    }//GEN-LAST:event_BubbleActionPerformed

    private void QuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickActionPerformed
        if (dateTimeImage == null || dateTimeImage.isEmpty()) return;
        ordenarComContagem("quick");
    }//GEN-LAST:event_QuickActionPerformed

    
    private void ordenarComContagem(String metodo) {
        new Thread(() -> {
            boolean rodando = true;
            long oldTime = System.nanoTime();
            long tempoInicial = oldTime;
            double tempoTotal = 0;
            double deltaTime;
            double segundos = 0;

            SwingUtilities.invokeLater(() -> setTitle("Ordenando com " + metodo + "..."));

            switch (metodo) {
                case "insertion":
                    insertionSort(dateTimeImage);
                    break;
                case "bubble":
                    bubbleSort(dateTimeImage);
                    break;
                case "quick":
                    quickSort(dateTimeImage, 0, dateTimeImage.size() - 1);
                    break;
            }

            long tempoFinal = System.nanoTime();
            rodando = false;

            tempoTotal = (tempoFinal - tempoInicial) / 1000000000.0;

            final double tempo = tempoTotal;
            SwingUtilities.invokeLater(() -> {
                JListUpdateData();
                setTitle("Ordenado com " + metodo + " em " + String.format("%.6f", tempo) + "s");
            });
        }).start();
    }

    
    
    private void JListUpdateData(){
        listModel.clear();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        for (ImageData item : dateTimeImage) {
            listModel.addElement(sdf.format(item.getDateTime()));
        }

        if (!dateTimeImage.isEmpty()) {
            currentIndex = 0;
            jList1.setSelectedIndex(0);
            showImageAtIndex(0);
        }
    }
    
    private void insertionSort(List<ImageData> list) {
        for (int i = 1; i < list.size(); i++) {
            ImageData key = list.get(i);
            int j = i - 1;
            while (j >= 0 && list.get(j).getDateTime().after(key.getDateTime())) {
                list.set(j + 1, list.get(j));
                j--;
            }
            list.set(j + 1, key);
        }
    }

    private void bubbleSort(List<ImageData> list) {
        int n = list.size();
        boolean swapped;
        for (int i = 0; i < n - 1; i++) {
            swapped = false;
            for (int j = 0; j < n - i - 1; j++) {
                if (list.get(j).getDateTime().after(list.get(j + 1).getDateTime())) {
                    ImageData temp = list.get(j);
                    list.set(j, list.get(j + 1));
                    list.set(j + 1, temp);
                    swapped = true;
                }
            }
            if (!swapped) break;
        }
    }

    private void quickSort(List<ImageData> list, int low, int high) {
        if (low < high) {
            int pi = partition(list, low, high);
            quickSort(list, low, pi - 1);
            quickSort(list, pi + 1, high);
        }
    }

    private int partition(List<ImageData> list, int low, int high) {
        ImageData pivot = list.get(high);
        int i = (low - 1);
        for (int j = low; j < high; j++) {
            if (list.get(j).getDateTime().before(pivot.getDateTime())) {
                i++;
                ImageData temp = list.get(i);
                list.set(i, list.get(j));
                list.set(j, temp);
            }
        }
        ImageData temp = list.get(i + 1);
        list.set(i + 1, list.get(high));
        list.set(high, temp);
        return i + 1;
    }
    
    private void showImageAtIndex(int index) {
        if (index < 0 || index >= dateTimeImage.size()) {
            jLabel1.setIcon(null);
            return;
        }

        Timestamp item = dateTimeImage.get(index).getDateTime();
        ImagesDAO img = new ImagesDAO();
        try {
            byte[] imgBytes = img.getImage(item);
            if (imgBytes == null || imgBytes.length == 0) {
                jLabel1.setIcon(null);
                System.out.println("Imagem vazia no índice: " + index);
                return;
            }

            BufferedImage image = ImageIO.read(new ByteArrayInputStream(imgBytes));
            if (img != null) {
                jLabel1.setIcon(new ImageIcon(
                        image.getScaledInstance(
                                jLabel1.getWidth(),
                                jLabel1.getHeight(),
                                java.awt.Image.SCALE_SMOOTH
                        )
                ));
            } else {
                jLabel1.setIcon(null);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            jLabel1.setIcon(null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GetImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GetImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GetImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GetImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GetImages().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Anterior;
    private javax.swing.JButton Bubble;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Inserction;
    private javax.swing.JButton Proximo;
    private javax.swing.JButton Quick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
